### ISSUE TITLE
[Uglify] should uglify ALL files, even in bower components

### ISSUE THREAD

**Issue by iliqportals** [studyportals/product-deploy#23]
Currently it is excluding bower_components

**Comment by CZYK** [comment]
There is a good reason to exclude `bower_components` since those packages are ready to be used without modification. In principle all packages should expose a full version and a minified/uglified version. Keep in mind that there are a sh*tload of js files in `bower_components` so it will take significant more time to uglify all of them.

It would be a better approach — in my opinion — to let [Packer](https://github.com/studyportals/CMS/blob/643522a5f54b0ac88c527745d61647e2e9ba2ad1/src/Router.php#L802) handle this.

**Comment by iliqportals** [comment]
Only dist files need to be processed, as those are served out
Another thing to keep in mind: Our code does not allow for .min files. This is why we need to uglify everything.
Portals are not using bower, so it might be even better to remove their bower dependencies

Another **Important** dirctory is the Vendor. (mootools as an example) must be minified
Everything under the project MUST be minified, no matter how it is served out.
If a package offers sub packages, they must be treaded as sub projects ( minify *, except node_modules/**, bower/**/src)

The main issue is that Packer just Packs, it should not do any extra on runtime steps. that is why we deploy.

**Comment by CZYK** [comment]
I am currently setting up the [sass package](https://github.com/studyportals/sass) to accept globs for `from` and `to` parameters as requested in https://github.com/studyportals/product-deploy/issues/6
This way the implementation can decide on what to include or exclude. Will do the same thing for https://github.com/studyportals/product-deploy/issues/7
